apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: emwz3s64n-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:f2fd1190ca25c5af0aec70c22a94cd4ebfdd7c6d@sha256:ec8d8c4c7c195bdd0bb569ab192f799d93f9aee0663f30784f5d0d9a0ced77b4
          name: container-image
